### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by ohmpsy** [ygoreplay/pro-server#2]
how run the server?

Error: Webpack compilation errors
    at /home/travis/build/ohmpsy/pro-server/tools/lib/runWebpack.ts:12:31

**Comment by async3619** [comment]
I just checked your travis logs and it seems you didn't provide environment variables for Sentry support.

In order to build this project automatically, You should provide following environment variables:

- `SENTRY_AUTH_TOKEN`
- `SENTRY_DSN`
- `SENTRY_ORG`
- `SENTRY_PROJECT`
- `SENTRY_URL`
